### PR TITLE
Swift 3.0/iOS 10 Support

### PR DESCRIPTION
**Pull request by RishabhTayal**
Support for Swift 3.0

### CODE REVIEW

**Comment by RishabhTayal** [comment]
@MengTo updated the branch and tested the sample app. Runs fine. Please test and merge.

**Comment by MengTo** [comment]
Thanks for the PR! Can you submit to a swift3 branch instead of master?

**Comment by RishabhTayal** [comment]
@MengTo I don't think I have access to create a new branch on your repository. How can I create a pull request to a branch which doesn't exists? Can you create a branch `swift3` from master? I will create a PR then.

**Comment by MengTo** [comment]
Done, please submit to swift3. Thanks!

**Comment by RishabhTayal** [comment]
Please refer to https://github.com/MengTo/Spring/pull/179

**Pull request closed without merging**
