### PR TITLE
Added repeatCount as an editable property

### PR DESCRIPTION
**Pull request by imkevinxu**
Thought this might be useful

### CODE REVIEW

**Comment by MengTo** [comment]
Okay, let me give this a test. Thanks, that was fast!

**Comment by imkevinxu** [comment]
Only bug I found was I couldn't add `HUGE` or `INFINITY` into the InterfaceBuilder attribute area so I just ended up using 999

**Comment by MengTo** [comment]
That's fine. I think resetAll needs it to make sure that it can chain and that it doesn't get properties from stored animations.

**Comment by imkevinxu** [comment]
Made the change, good call :+1:

**Pull request merged**
