### PR TITLE
Added extension for UIColor

### PR DESCRIPTION
**Pull request by giacomopiva**
Added a fromHexString class method

### CODE REVIEW

**Comment by jamztang** [comment]
Looks like a duplication feature inside Misc.swift

https://github.com/MengTo/Spring/blob/master/Spring/Misc.swift#L59-L102

**Comment by giacomopiva** [comment]
Ok, I see I can improve the existing one.
If you agree I can make it #-safe

**Comment by jamztang** [comment]
I'm sure that would be a welcome improvement :)

**Comment by giacomopiva** [comment]
I made my little changes, and I also updated the example App to test changes

**Comment by giacomopiva** [comment]
Don't you like my changes?

**Comment by MengTo** [comment]
So the changes make it so that it works both with # or without #?

**Comment by giacomopiva** [comment]
With and without the # 



—
G.

**Comment by MengTo** [comment]
Awesome, thanks!

**Pull request merged**
