### PR TITLE
Fixed Some bugs in Swift1.2

### PR DESCRIPTION
**Pull request by nirvana1314**
Fixed Some bugs in Xocde 6.3 beta2(Swift1.2).  I think the reason that Swift changed method.Most like "as" -> as!, the Optional type ...

### CODE REVIEW

**Comment by nirvana1314** [comment]
Fixed Some bugs in Xocde 6.3 beta2(Swift1.2). I think the reason that Swift changed method.Most like "as" -> as!, the Optional type ...

**Comment by jamztang** [comment]
@nirvana1314 can we leave the file permission untouched?

**Comment by nirvana1314** [comment]
OK

**Comment by jamztang** [comment]
So 1.2 is still in beta so we'll not merge to master until then. Would you like to submit a new patch that reverts the file permissions?

**Pull request closed without merging**
