### PR TITLE
Swift2: BlurView returns the view

### PR DESCRIPTION
**Pull request by ricardopereira**
Practical use:
`insertBlurView(view, style: .Dark).addGestureRecognizer(gestureRecognizer)`

### CODE REVIEW

**Comment by schneiderandre** [comment]
Hey @ricardopereira, thanks for your pull request! It looks like this Pull Request was already merged in #91 on the master branch. Since both branches will be merged together, we don't need to do the same on both branches.
If that’s not right, please re-open this one. Thanks again! :smile:

**Comment by ricardopereira** [comment]
@schneiderandre Yes, that's right but I'm also using Swift 2 and I saw it's a work in progress. When will you merge the branch with the master?

**Comment by schneiderandre** [comment]
I see. We could merge the master into the swift2 branch to be up to date there.
What do you think?

**Comment by ricardopereira** [comment]
That sounds great :smile:

**Comment by schneiderandre** [comment]
Great! There are some merge conflicts, let's hope I can resolve them quickly :pray:

**Comment by schneiderandre** [comment]
@ricardopereira, merged! give it a try :+1:

**Comment by ricardopereira** [comment]
That was fast. It compiles successfully ihih :+1:
Thank you.

**Comment by schneiderandre** [comment]
You are welcome! :smile:

**Pull request closed without merging**
