### PR TITLE
prevents retain cycle

### PR DESCRIPTION
**Pull request by camitox**
based on what I said here:

https://github.com/MengTo/Spring/issues/16

The views were retaining the Spring, and the Spring was also retaining the view.

### CODE REVIEW

**Comment by jamztang** [comment]
Thanks @camitox. Great catch!

The patch does solves retain cycle but it's triggering a crash after deinit. I suspect we'll just need to make a few more lines of changes.
screen shot 2015-02-03 at 12 14 38 pm

**Comment by camitox** [comment]
Oh, my bad.. Tomorrow I will play with it a bit more

**Comment by jamztang** [comment]
Not at all, we appreciate your contribution, that makes the library better and better :)

**Comment by camitox** [comment]
ok, that's because when the completion block is called, the Spring is already nil (since is unowned). using 

```
{ [weak self] in 
    //block code..
}
```

it's a good way to avoid that kind of crashes using blocks.

**Comment by jamztang** [comment]
Looks good to me! Thanks a lot @camitox

**Comment by jamztang** [comment]
Merging this closes #16.

**Pull request merged**
