### PR TITLE
Add a shared Xcode scheme for the Spring framework target

### PR DESCRIPTION
**Pull request by rastersize**
This PR adds a shared Xcode scheme for the Spring framework target. Such a file makes Spring work with [Carthage](https://github.com/Carthage/Carthage) (a dependency manager) as well as potentially continuous integration systems like [Travis-CI](travis-ci.org)*.

Further it removes a few Xcode project files which were committed to the repository before the git ignore file was added. Lastly the PR will also decrease the deployment target of the Spring framework target to iOS 8.0. It was set to 8.1 before while the SpringApp target was set to 8.0.

*) This would still require some more addition to the repository as well as configuring such system and the GitHub repository.

### CODE REVIEW

**Comment by jamztang** [comment]
Carthage build the branch correctly, but I'm seeing this error message.
```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/mobile/Containers/Bundle/Application/19B1CF62-41DC-4BBA-9969-38460E44BCB4/ObjectiveSpring.app/Frameworks/Spring.framework/Spring
  Reason: image not found
````
I followed suggested steps from [stackoverflow](http://stackoverflow.com/questions/24002836/dyld-library-not-loaded-rpath-libswift-stdlib-core-dylib) but it doesn't solve my problem.

I'm not sure if there's more thing to do with the setup or it's the problem of Carthage.
My sample project is attached [here](https://github.com/JTExperiments/ObjectiveSpring)

**Comment by clooth** [comment]
I didn't see any problems with this. I forked Spring, added the shared scheme and used that with Carthage and it worked just fine.

**Comment by jamztang** [comment]
Possibly on an Objective-C project. We'll get a try and revert.

**Comment by jamztang** [comment]
Yes it's working on an Swift based project. There's still issues when I tried using Spring this way, we shall further discuss in #11

**Pull request merged**
